#pragma once
#include "CoreMinimal.h"
#include "ETWDAchievement.generated.h"

UENUM(BlueprintType)
enum class ETWDAchievement : uint8 {
    TWDSS_OverEncumbered,
    TWDSS_YouWearIntestinesWell,
    TWDSS_TheHugger,
    TWDSS_Completionist,
    TWDSS_MasterOfTheCraft,
    TWDSS_FullGearTable,
    TWDSS_FullSurvivalTable,
    TWDSS_FullGunTable,
    TWDSS_ScrewLoose,
    TWDSS_AxemanJazz,
    TWDSS_NeganDozen,
    TWDSS_PropaneAccessories,
    TWDSS_Sinner,
    TWDSS_Brains,
    TWDSS_GhostWalker,
    TWDSS_TruffleShuffle,
    TWDSS_FoodJunkie,
    TWDSS_MasterChef,
    TWDSS_Hypochondriac,
    TWDSS_TheConnoisseur,
    TWDSS_HonoraryWhisperer,
    TWDSS_ChalkUp,
    TWDSS_SafeCracker,
    TWDSS_AllAngelsSaints,
    TWDSS_BloodBathBeyond,
    TWDSS_TheTourist,
    TWDSS_Pyro,
    TWDSS_Arsonist,
    TWDSS_BourbonStreetPharmacist,
    TWDSS_TheStig,
    TWDSS_ImproviseAdaptOvercome,
    TWDSS_PewPew,
    TWDSS_HardCore,
    TWDSS_NoReservations,
    TWDSS_ForWhomTheBellsToll,
    TWDSS_FlyLikeAPelican,
    TWDSS_ShakenNotStirred,
    TWDSS_Saint,
    TWDSS_MeetJB,
    TWDSS_MeetGeorgia,
    TWDSS_ContactCasey,
    TWDSS_MeetMay,
    TWDSS_RepairTheFirstPump,
    TWDSS_GetTheKeyForReserve,
    TWDSS_FindAmbreDrawing,
    TWDSS_AchievementMAX,
    TWDSS_MAX UMETA(Hidden),
};

